on: [push]

name: test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.0.8

      - name: Set Env Vars
        env:
          MASTER_COPY_ADDRESS: "0xd4a1E956fFe2D07CD71c8fABf538f2BfC0e3899B"
          PROXY_FACTORY_ADDRESS: "0xEAb613456d3efD309101BB02872BEdCecE2879E2"
          KEYPER_MODULE_ADDRESS: "0xc74f6cAFb3e89006FE9c0E8Be8Dc06888e178F1b"
          OWNER_1: "0x9CDd325E49A6a8a82288fdC3B6C14b25221D1Cfa"
          OWNER_2: "0xEd4AD3605740D6a9232e05F4d8A2b3377f81a8AA"
          THRESHOLD: 1
          FOUNDRY_VIA_IR: true
        run: |
          touch .env
          echo "MASTER_COPY_ADDRESS=$MASTER_COPY_ADDRESS" >> .env
          echo "PROXY_FACTORY_ADDRESS=$PROXY_FACTORY_ADDRESS" >> .env
          echo "KEYPER_MODULE_ADDRESS=$KEYPER_MODULE_ADDRESS" >> .env
          echo "OWNER_1=$OWNER_1" >> .env
          echo "OWNER_2=$OWNER_2" >> .env
          echo "THRESHOLD=$THRESHOLD" >> .env
          echo "FOUNDRY_VIA_IR=$FOUNDRY_VIA_IR" >> .env

      - name: Run Tests
        run: forge test --no-match-contract StressTestStorage

      - name: Run Coverage
        run: forge coverage --no-match-contract StressTestStorage
